name: Tests
on:
  pull_request:
    paths-ignore: ['dist/**', '*.md']
  push:
    branches: [main, 0.9.x, ci]
    paths-ignore: ['dist/**', '*.md']
jobs:
  test:
    name: ${{ matrix.os[0] }}, PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}, ${{ matrix.dependencies }}
    runs-on: ${{ matrix.os[1] }}
    strategy:
      matrix:
        os: [[Ubuntu, ubuntu-latest], [Windows, windows-latest]]
        php: ['7.3', '7.4', '8.0', '8.1']
        laravel: [5.5.*, 5.6.*, 5.7.*, 5.8.*, 6.*, 7.*, 8.*, 9.*]
        dependencies: [lowest, highest]
        exclude:
          - php: '7.3'
            laravel: 9.*
          - php: '7.4'
            laravel: 9.*
          - php: '8.0'
            laravel: 5.5.*
          - php: '8.0'
            laravel: 5.6.*
          - php: '8.0'
            laravel: 5.7.*
          - php: '8.0'
            laravel: 5.8.*
          - php: '8.1'
            laravel: 5.5.*
          - php: '8.1'
            laravel: 5.6.*
          - php: '8.1'
            laravel: 5.7.*
          - php: '8.1'
            laravel: 5.8.*
          - php: '8.1'
            laravel: 6.*
          - php: '8.1'
            laravel: 7.*
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo, json
      - run: composer require laravel/framework:"${{ matrix.laravel }}" --no-update --no-interaction
      - uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
      - run: vendor/bin/phpunit --testdox --colors=always
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci && npm run build
      - run: npm test
